//get all posts
GET http://localhost:9090/api/v1/post/all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt1c2hhbmdheWFudGhhMTIzNDVAZ21haWwuY29tIiwibmFtZSI6Imt1c2hhbjJrIiwiaWQiOiI5ZjlmYTdiOC1kYTM4LTQyYWEtODEzMC01YTQ0OWRmNDZlMGUiLCJpYXQiOjE2OTUzNjg3NjMsImV4cCI6MTY5NjIzMjc2MywiYXVkIjoidXNlciIsImlzcyI6ImxvY2FsaG9zdCJ9.Sx00rzaki8r50LLNSvuUN_yTXr8TE_kuncBgC28VmCI

###

POST http://localhost:9090/api/v1/post/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt1c2hhbmdheWFudGhhMTIzNDVAZ21haWwuY29tIiwibmFtZSI6Imt1c2hhbjJrIiwiaWQiOiI5ZjlmYTdiOC1kYTM4LTQyYWEtODEzMC01YTQ0OWRmNDZlMGUiLCJpYXQiOjE2OTUzNjg3NjMsImV4cCI6MTY5NjIzMjc2MywiYXVkIjoidXNlciIsImlzcyI6ImxvY2FsaG9zdCJ9.Sx00rzaki8r50LLNSvuUN_yTXr8TE_kuncBgC28VmCI

{
  "slug":"test post",
  "title":"my first post",
  "body":"hello world i'm new here"
  
}